[package]
name = "watchexec"
version = "1.5.0"
authors = ["Matt Green <mattgreenrocks@gmail.com>"]
description = "Executes commands in response to file modifications"
documentation = "https://github.com/mattgreen/watchexec"
homepage = "https://github.com/mattgreen/watchexec"
repository = "https://github.com/mattgreen/watchexec"
readme = "README.md"
keywords = ["watcher", "inotify", "fsevents", "kqueue"]
license = "Apache-2.0"

[profile.dev]
panic = "abort"

[profile.release]
lto = true
panic = "abort"

[dependencies]
globset = "0.1.2"
ignore = "0.1.5"
lazy_static = "0.2.1"
libc = "0.2.16"
log = "0.3.6"
notify = "3.0.0"

[dev-dependencies]
mktemp = "0.3.1"

[dependencies.clap]
version = "2.14"
default-features = false
features = ["wrap_help"]

[dependencies.env_logger]
version = "0.3.5"
default-features = false
features = []

[target.'cfg(unix)'.dependencies]
nix = "0.7.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"
kernel32-sys = "0.2.2"
